config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/new'
  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :tweets, dependent: :destroy

         attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!

	def after_sign_in_path_for(resource)
    	tweets_path # ログイン後に遷移するpathを設定
  	end

	def after_sign_out_path_for(resource)
    	new_user_session_path # ログアウト後に遷移するpathを設定
  	end

 	protected

  	def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def index
		@tweets = Tweet.all
		@tweet = Tweet.new
	end

	def new
		@tweet = Tweet.new
	end

	def create
		tweet = Tweet.new(tweet_params)
		tweet.user_id = current_user.id
		tweet.save
		redirect_to tweets_path
	end

	def destroy
		tweet = Tweet.find(params[:id])
		tweet.destroy
		redirect_to tweets_path
	end

	private
	def tweet_params
		params.require(:tweet).permit(:body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show
  	@user = User.find(params_id)
  	@tweet = Tweet.new
  	@tweets = @user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <div class="row">
          <div class="col-xs-6">
                <i class="glyphicon glyphicon-home"></i>
                <li class="nav-list-item">Home</li>
                <i class="glyphicon glyphicon-flash"></i>
                <li class="nav-list-item">Moments</li>
                <i class="glyphicon glyphicon-bell"></i>
                <li class="nav-list-item">Notifications</li>
                <i class="glyphicon glyphicon-envelope"></i>
                <li class="nav-list-item">Messages</li>
          </div>
          <div class="col-xs-2">
            <i class="fa fa-twitter"></i>
          </div>
          <div class="col-xs-4">
            <% if user_signed_in? %>
              <%= link_to 'サインアウト', destroy_user_session_path, method: :delete %>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <%= yield %>

  </body>
</html>

app/views/tweets/index.html.erb
<div class="main-content">
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<div class="user-profile-area">
				<%= current_user.name %>
			</div>

			<div class="weather-area">
				Weather
			</div>
		</div>


		<div class="middle-area col-lg-6">
			<div class="tweet-post">
				<%= form_for(@tweet) do |f| %>
					<%= f.text_field :body %>
					<%= f.submit 'Tweet' %>
				<% end %>
			</div>

			<table class ="table table-hover table-inverse">
				<tbody>
					<% @tweets.each do |tweet| %>
					<tr>
						<td></td>
						<td><%= tweet.user.name %><br>
							<%= tweet.body %>
							<%= link_to 'ツイートを削除', tweet_path(tweet), method: :delete %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>

		<div class="col-xs-3">
		</div>
	</div>

</div>
</div>

app/views/tweets/new.html.erb
<h1>Compose new Tweet</h1>
<%= form_for (@tweet) do |f| %>
	<%= f.text_area :body %>
	<%= f.submit 'Tweet' %>
<% end %>
<%= link_to '戻る', tweets_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="main-content">
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<div class="user-profile-area">
				<%= current_user.name %>
			</div>

			<div class="weather-area">
				Weather
			</div>
		</div>


		<div class="middle-area col-lg-6">
			<div class="tweet-post">
				<%= form_for(@tweet) do |f| %>
					<%= f.text_field :body %>
					<%= f.submit 'Tweet' %>
				<% end %>
			</div>

			<table class ="table table-hover table-inverse">
				<tbody>
					<% @tweets.each do |tweet| %>
					<tr>
						<td></td>
						<td><%= current_user.name %><br>
							<%= tweet.body %>
							<%= link_to 'ツイートを削除', tweet_path(tweet), method: :delete %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>

		<div class="col-xs-3">
		</div>
	</div>

</div>
</div>